# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Use the version of Java you are using
          distribution: 'temurin'

      - name: Build the project
        run: |
          mkdir -p bin  # Ensure the bin directory exists
          find src -name "*.java" > sources.txt  # Find all Java files
          javac -d bin @sources.txt  # Compile using the list of source files

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/ferryrama/credit-simulator:v1.0.0 .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/ferryrama/credit-simulator:v1.0.0